import type { AgentFramework } from "./types";

export const AGENT_FRAMEWORKS: AgentFramework[] = [
  {
    id: "python",
    name: "Python Agent",
    description: "Build custom agents with Python scripts and libraries",
    icon: "FileCode2",
    complexity: "intermediate",
    language: "python",
    fileTypes: [".py", ".zip"],
  },
  {
    id: "langchain",
    name: "LangChain",
    description: "Build LLM-powered agents with LangChain framework",
    icon: "Link",
    complexity: "intermediate",
    language: "python",
    fileTypes: [".py", ".json", ".yaml", ".zip"],
  },
  {
    id: "autogen",
    name: "AutoGen",
    description: "Multi-agent conversations with Microsoft AutoGen",
    icon: "Users",
    complexity: "advanced",
    language: "python",
    fileTypes: [".py", ".json", ".zip"],
  },
  {
    id: "crewai",
    name: "CrewAI",
    description: "Role-based AI agent crews for complex tasks",
    icon: "UsersRound",
    complexity: "advanced",
    language: "python",
    fileTypes: [".py", ".yaml", ".zip"],
  },
  {
    id: "semantic-kernel",
    name: "Semantic Kernel",
    description: "Microsoft Semantic Kernel for enterprise AI agents",
    icon: "Cpu",
    complexity: "advanced",
    language: "python",
    fileTypes: [".py", ".json", ".zip"],
  },
  {
    id: "openai-functions",
    name: "OpenAI Functions",
    description: "Function-calling agents using OpenAI API",
    icon: "Sparkles",
    complexity: "beginner",
    language: "python",
    fileTypes: [".py", ".json", ".zip"],
  },
  {
    id: "llamaindex",
    name: "LlamaIndex",
    description: "Data-aware agents with LlamaIndex RAG pipelines",
    icon: "Database",
    complexity: "intermediate",
    language: "python",
    fileTypes: [".py", ".json", ".zip"],
  },
  {
    id: "n8n",
    name: "n8n Workflow",
    description: "Import and run n8n automation workflows",
    icon: "Workflow",
    complexity: "beginner",
    language: "javascript",
    fileTypes: [".json"],
  },
  {
    id: "nodejs",
    name: "Node.js Agent",
    description: "Build agents with Express.js and Node.js",
    icon: "Server",
    complexity: "intermediate",
    language: "javascript",
    fileTypes: [".js", ".json", ".zip"],
  },
  {
    id: "rest-api",
    name: "Custom REST Agent",
    description: "Connect any REST API as an executable agent",
    icon: "Globe",
    complexity: "beginner",
    language: "javascript",
    fileTypes: [".json", ".yaml"],
  },
  {
    id: "no-code",
    name: "No-Code Builder",
    description: "Visual drag-and-drop agent builder — no coding required",
    icon: "MousePointerClick",
    complexity: "beginner",
    language: "no-code",
    fileTypes: [],
  },
];

export const COMPLEXITY_LABELS: Record<string, { label: string; color: string }> = {
  beginner: { label: "Beginner", color: "text-green-600 bg-green-500/10" },
  intermediate: { label: "Intermediate", color: "text-yellow-600 bg-yellow-500/10" },
  advanced: { label: "Advanced", color: "text-red-600 bg-red-500/10" },
};

export const NODE_TYPES = [
  { type: "input" as const, label: "Input", icon: "ArrowDownToLine", color: "bg-blue-500" },
  { type: "llm" as const, label: "LLM", icon: "Brain", color: "bg-purple-500" },
  { type: "api_call" as const, label: "API Call", icon: "Globe", color: "bg-green-500" },
  { type: "tool" as const, label: "Tool", icon: "Wrench", color: "bg-orange-500" },
  { type: "condition" as const, label: "Condition", icon: "GitBranch", color: "bg-yellow-500" },
  { type: "output" as const, label: "Output", icon: "ArrowUpFromLine", color: "bg-red-500" },
];
