import type { Agent } from "./types";

export interface TrendingAgent extends Agent {
  runs_count: number;
  rating: number;
  creator_name: string;
  trending_rank: number;
  // Extended details
  use_cases: string[];
  pricing: "free" | "paid" | "subscription";
  pricing_label: string;
  requires_api: boolean;
  reviews_count: number;
  sensitive_permissions: string[];
}

export const trendingAgents: TrendingAgent[] = [
  {
    id: "trending-1",
    name: "AutoCoder Pro",
    description:
      "AI-powered code generation agent that writes, reviews, and refactors code across 20+ languages. Integrates with GitHub for seamless PR workflows.",
    category: "development",
    icon_url: null,
    creator_id: "creator-1",
    is_public: true,
    version: "2.4",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "GitHub Access", description: "Read/write repository access", required: true },
    ],
    tools: ["github", "code-analysis", "linter"],
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-28T14:00:00Z",
    runs_count: 48520,
    rating: 4.9,
    creator_name: "DevForge Labs",
    trending_rank: 1,
    use_cases: [
      "Generate boilerplate code from natural language prompts",
      "Automated PR review with inline suggestions",
      "Refactor legacy codebases across languages",
      "Generate unit tests for existing functions",
    ],
    pricing: "subscription",
    pricing_label: "$19/mo",
    requires_api: true,
    reviews_count: 1247,
    sensitive_permissions: ["GitHub Access"],
  },
  {
    id: "trending-2",
    name: "DataPipe ETL",
    description:
      "Automated data extraction, transformation, and loading agent. Connects to 50+ data sources including SQL, NoSQL, APIs, and spreadsheets.",
    category: "data",
    icon_url: null,
    creator_id: "creator-2",
    is_public: true,
    version: "3.1",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "Database Access", description: "Connect to your databases", required: true },
    ],
    tools: ["sql-connector", "api-bridge", "csv-parser"],
    created_at: "2025-11-20T08:00:00Z",
    updated_at: "2026-03-30T09:00:00Z",
    runs_count: 37890,
    rating: 4.8,
    creator_name: "PipelineIO",
    trending_rank: 2,
    use_cases: [
      "Migrate data between SQL and NoSQL databases",
      "Schedule recurring ETL jobs from APIs to warehouses",
      "Transform and clean CSV/spreadsheet data at scale",
      "Sync third-party SaaS data into your data lake",
    ],
    pricing: "paid",
    pricing_label: "$0.02/run",
    requires_api: true,
    reviews_count: 892,
    sensitive_permissions: ["Database Access"],
  },
  {
    id: "trending-3",
    name: "SocialPulse AI",
    description:
      "Monitors social media trends, generates engagement reports, and auto-schedules posts across Twitter/X, LinkedIn, and Instagram.",
    category: "communication",
    icon_url: null,
    creator_id: "creator-3",
    is_public: true,
    version: "1.8",
    execution_type: "API",
    config: {},
    permissions: [
      { name: "Social Accounts", description: "Access to your social media accounts", required: true },
    ],
    tools: ["twitter-api", "linkedin-api", "sentiment-analysis"],
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-04-01T16:00:00Z",
    runs_count: 31450,
    rating: 4.7,
    creator_name: "GrowthStack",
    trending_rank: 3,
    use_cases: [
      "Track brand mentions and sentiment across platforms",
      "Auto-schedule posts at optimal engagement times",
      "Generate weekly social media performance reports",
      "Monitor competitor activity and trending hashtags",
    ],
    pricing: "subscription",
    pricing_label: "$29/mo",
    requires_api: true,
    reviews_count: 654,
    sensitive_permissions: ["Social Accounts"],
  },
  {
    id: "trending-4",
    name: "InfraWatch",
    description:
      "Real-time infrastructure monitoring agent. Detects anomalies, auto-scales resources, and sends intelligent alerts via Slack, PagerDuty, or email.",
    category: "automation",
    icon_url: null,
    creator_id: "creator-4",
    is_public: true,
    version: "4.0",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "Cloud Access", description: "AWS/GCP/Azure credentials", required: true },
    ],
    tools: ["cloudwatch", "prometheus", "slack-webhook"],
    created_at: "2025-09-10T06:00:00Z",
    updated_at: "2026-03-29T11:00:00Z",
    runs_count: 28900,
    rating: 4.9,
    creator_name: "CloudOps Inc",
    trending_rank: 4,
    use_cases: [
      "24/7 infrastructure health monitoring with anomaly detection",
      "Auto-scale cloud resources based on traffic patterns",
      "Intelligent alerting to Slack, PagerDuty, or email",
      "Cost optimization recommendations for cloud spend",
    ],
    pricing: "subscription",
    pricing_label: "$49/mo",
    requires_api: true,
    reviews_count: 1089,
    sensitive_permissions: ["Cloud Access"],
  },
  {
    id: "trending-5",
    name: "DocuMind",
    description:
      "Intelligent document processing agent. Extracts data from PDFs, invoices, contracts, and forms using OCR and NLP with 99.2% accuracy.",
    category: "ai",
    icon_url: null,
    creator_id: "creator-5",
    is_public: true,
    version: "2.0",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "File Access", description: "Read uploaded documents", required: true },
    ],
    tools: ["ocr-engine", "nlp-extractor", "pdf-parser"],
    created_at: "2025-12-05T14:00:00Z",
    updated_at: "2026-04-02T08:00:00Z",
    runs_count: 25670,
    rating: 4.8,
    creator_name: "AI Docs Co",
    trending_rank: 5,
    use_cases: [
      "Extract structured data from invoices and receipts",
      "Parse and classify legal contracts automatically",
      "Digitize paper forms with OCR and field detection",
      "Batch process hundreds of PDFs for data extraction",
    ],
    pricing: "paid",
    pricing_label: "$0.05/page",
    requires_api: false,
    reviews_count: 743,
    sensitive_permissions: ["File Access"],
  },
  {
    id: "trending-6",
    name: "EmailGenius",
    description:
      "AI email assistant that drafts, personalizes, and sends cold outreach campaigns. A/B tests subject lines and optimizes send times.",
    category: "communication",
    icon_url: null,
    creator_id: "creator-6",
    is_public: true,
    version: "1.5",
    execution_type: "API",
    config: {},
    permissions: [
      { name: "Email Access", description: "SMTP or email API credentials", required: true },
    ],
    tools: ["smtp-sender", "ab-tester", "personalization-engine"],
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-03-31T13:00:00Z",
    runs_count: 22340,
    rating: 4.6,
    creator_name: "OutreachAI",
    trending_rank: 6,
    use_cases: [
      "Draft personalized cold outreach at scale",
      "A/B test subject lines for optimal open rates",
      "Schedule email campaigns with smart send-time optimization",
      "Auto-generate follow-up sequences based on engagement",
    ],
    pricing: "subscription",
    pricing_label: "$15/mo",
    requires_api: true,
    reviews_count: 512,
    sensitive_permissions: ["Email Access"],
  },
  {
    id: "trending-7",
    name: "TestRunner AI",
    description:
      "Automated testing agent that generates unit, integration, and E2E tests. Supports Jest, Pytest, Cypress, and Playwright frameworks.",
    category: "development",
    icon_url: null,
    creator_id: "creator-7",
    is_public: true,
    version: "1.9",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "Repository Access", description: "Clone and read your codebase", required: true },
    ],
    tools: ["test-generator", "coverage-analyzer", "ci-integration"],
    created_at: "2026-02-10T11:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
    runs_count: 19870,
    rating: 4.7,
    creator_name: "QualityFirst",
    trending_rank: 7,
    use_cases: [
      "Generate unit tests from function signatures",
      "Create E2E test suites for web applications",
      "Analyze code coverage and suggest missing tests",
      "Integrate with CI/CD pipelines for automated testing",
    ],
    pricing: "free",
    pricing_label: "Free",
    requires_api: false,
    reviews_count: 389,
    sensitive_permissions: ["Repository Access"],
  },
  {
    id: "trending-8",
    name: "FlowBuilder",
    description:
      "Visual workflow automation agent. Connects apps like Notion, Slack, Google Sheets, and Airtable with natural language instructions.",
    category: "automation",
    icon_url: null,
    creator_id: "creator-8",
    is_public: true,
    version: "2.2",
    execution_type: "N8N",
    config: {},
    permissions: [
      { name: "App Connections", description: "OAuth tokens for connected apps", required: true },
    ],
    tools: ["n8n-workflow", "oauth-manager", "webhook-listener"],
    created_at: "2025-10-15T07:00:00Z",
    updated_at: "2026-03-27T15:00:00Z",
    runs_count: 17650,
    rating: 4.5,
    creator_name: "AutomateHQ",
    trending_rank: 8,
    use_cases: [
      "Connect Notion, Slack, and Google Sheets with one command",
      "Build multi-step workflows without coding",
      "Trigger automations from webhooks or schedules",
      "Sync data between 50+ SaaS applications",
    ],
    pricing: "free",
    pricing_label: "Free",
    requires_api: true,
    reviews_count: 298,
    sensitive_permissions: ["App Connections"],
  },
  {
    id: "trending-9",
    name: "InsightMiner",
    description:
      "Business intelligence agent that analyzes your data, generates dashboards, and surfaces actionable insights with natural language queries.",
    category: "data",
    icon_url: null,
    creator_id: "creator-9",
    is_public: true,
    version: "1.6",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "Data Source", description: "Access to your analytics data", required: true },
    ],
    tools: ["chart-generator", "sql-query", "trend-detector"],
    created_at: "2026-01-05T13:00:00Z",
    updated_at: "2026-04-02T12:00:00Z",
    runs_count: 15230,
    rating: 4.6,
    creator_name: "DataViz Labs",
    trending_rank: 9,
    use_cases: [
      "Ask questions about your data in plain English",
      "Auto-generate dashboards from raw datasets",
      "Detect trends and anomalies in business metrics",
      "Export reports as PDF or interactive web dashboards",
    ],
    pricing: "paid",
    pricing_label: "$0.10/query",
    requires_api: true,
    reviews_count: 421,
    sensitive_permissions: ["Data Source"],
  },
  {
    id: "trending-10",
    name: "SecScan Pro",
    description:
      "Security scanning agent that audits your codebase for vulnerabilities, checks dependencies, and generates compliance reports.",
    category: "development",
    icon_url: null,
    creator_id: "creator-10",
    is_public: true,
    version: "3.0",
    execution_type: "CONTAINER",
    config: {},
    permissions: [
      { name: "Repository Access", description: "Read access to scan your code", required: true },
    ],
    tools: ["sast-scanner", "dependency-checker", "compliance-reporter"],
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-03-30T17:00:00Z",
    runs_count: 13890,
    rating: 4.8,
    creator_name: "ShieldSec",
    trending_rank: 10,
    use_cases: [
      "Scan codebases for OWASP Top 10 vulnerabilities",
      "Audit dependencies for known CVEs",
      "Generate SOC 2 and ISO 27001 compliance reports",
      "Continuous security monitoring in CI/CD pipelines",
    ],
    pricing: "subscription",
    pricing_label: "$39/mo",
    requires_api: false,
    reviews_count: 567,
    sensitive_permissions: ["Repository Access"],
  },
];
